###############################################################################
# Copyright 2018 Samsung Electronics All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################

################ C AML DataModel build script ##################
import os
Import('env')

caml_sample_env = env.Clone()
target_arch = caml_sample_env.get('TARGET_ARCH')

######################################################################
# Build flags
######################################################################
caml_sample_env.PrependUnique(CPPPATH=[
    '../include'
])

caml_sample_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++0x', '-I/usr/local/include'])

if caml_sample_env.get('RELEASE'):
    caml_sample_env.PrependUnique(LIBS=['aml'], LIBPATH=[os.path.join('./../dependencies/datamodel-aml-cpp/out/linux/', target_arch, 'release')])
else:
    caml_sample_env.PrependUnique(LIBS=['aml'], LIBPATH=[os.path.join('./../dependencies/datamodel-aml-cpp/out/linux/', target_arch, 'debug')])

caml_sample_env.AppendUnique(LIBS=['caml'])

####################################################################
# Source files and Targets
######################################################################
camlsample = caml_sample_env.Program('sample', ['sample.c'])

Command("sample_data_model.aml", File("sample_data_model.aml").srcnode(), Copy("$TARGET", "$SOURCE"))